#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"
setxkbmap -model cp105 -layout es &

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"

cbatticon &
fcitx5 &
feh --bg-fill ~/Pictures/piccas_img/texture-background-surface-pattern-faded.jpg &
~/./pipewire-pulse &
xscreensaver --nosplash &
picom -cCGF &

exec fluxbox
